#!/bin/sh
# 为 AntiHub Plugin 服务创建独立的数据库和用户
# 此脚本由 PostgreSQL 官方镜像在首次初始化时自动执行

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
DO $$
BEGIN
    -- 支持 PLUGIN_DB_USER 与 POSTGRES_USER 相同（deploy.sh 默认复用超管账号）
    IF '${PLUGIN_DB_USER}' = '${POSTGRES_USER}' THEN
        EXECUTE format('ALTER USER %I WITH PASSWORD %L', '${POSTGRES_USER}', '${POSTGRES_PASSWORD}');
    ELSE
        IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${PLUGIN_DB_USER}') THEN
            EXECUTE format('CREATE USER %I WITH PASSWORD %L', '${PLUGIN_DB_USER}', '${PLUGIN_DB_PASSWORD}');
        ELSE
            EXECUTE format('ALTER USER %I WITH PASSWORD %L', '${PLUGIN_DB_USER}', '${PLUGIN_DB_PASSWORD}');
        END IF;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '${PLUGIN_DB_NAME}') THEN
        EXECUTE format('CREATE DATABASE %I OWNER %I', '${PLUGIN_DB_NAME}', '${PLUGIN_DB_USER}');
    ELSE
        EXECUTE format('ALTER DATABASE %I OWNER TO %I', '${PLUGIN_DB_NAME}', '${PLUGIN_DB_USER}');
    END IF;

    EXECUTE format('GRANT ALL PRIVILEGES ON DATABASE %I TO %I', '${PLUGIN_DB_NAME}', '${PLUGIN_DB_USER}');
END $$;

\c ${PLUGIN_DB_NAME}

DO $$
BEGIN
    EXECUTE format('GRANT ALL ON SCHEMA public TO %I', '${PLUGIN_DB_USER}');
    EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO %I', '${PLUGIN_DB_USER}');
    EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO %I', '${PLUGIN_DB_USER}');
END $$;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;
EOSQL
